steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--destination=${_GAR_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"
      - "--target=deploy"
      - "--cache=true"
      - "--cache-ttl=72h"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_GCR_SERVICE_NAME}"
      - "--image"
      - "${_GAR_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"
      - "--region"
      - "${_GCR_SERVICE_REGION}"
      - "--allow-unauthenticated"
  - name: "bufbuild/buf"
    dir: proto
    secretEnv:
      - "BUF_TOKEN"
    args:
      - "push"
substitutions:
  _GAR_REGION: europe-west1
  _GCR_SERVICE_NAME: badger-api
  _GCR_SERVICE_REGION: europe-west1
  _IMAGE: badger-api
  _REPOSITORY: badger
  _BUF_TOKEN_KEY: badger-buf-token-ci
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_BUF_TOKEN_KEY}/versions/latest
      env: BUF_TOKEN
options:
  dynamic_substitutions: true
timeout: 900s
